/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libfoza.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $955F1759725876F7F898C71A8A4DCDA3;
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4;

/* 1 */
struct __attribute__((aligned(8))) Elf64_Sym
{
  unsigned __int32 st_name;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
  unsigned __int64 st_value;
  unsigned __int64 st_size;
};

/* 2 */
struct Elf64_Rela
{
  unsigned __int64 r_offset;
  unsigned __int64 r_info;
  __int64 r_addend;
};

/* 3 */
struct Elf64_Dyn
{
  unsigned __int64 d_tag;
  unsigned __int64 d_un;
};

/* 4 */
struct __attribute__((aligned(4))) Elf64_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file;
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 5 */
struct __attribute__((aligned(4))) Elf64_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name;
  unsigned __int32 vna_next;
};

/* 6 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 7 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 8 */
typedef __n64 int8x8_t;

/* 9 */
typedef __n64 uint8x8_t;

/* 10 */
typedef __n64 int16x4_t;

/* 11 */
typedef __n64 int32x2_t;

/* 12 */
typedef __n64 uint16x4_t;

/* 13 */
typedef __n64 uint32x2_t;

/* 14 */
typedef __n128 int8x16_t;

/* 15 */
typedef __n128 int16x8_t;

/* 16 */
typedef __n128 int32x4_t;

/* 17 */
typedef __n128 int64x2_t;

/* 18 */
typedef __n128 uint8x16_t;

/* 19 */
typedef __n128 uint16x8_t;

/* 20 */
typedef __n128 uint32x4_t;

/* 21 */
typedef __n128 uint64x2_t;

/* 22 */
typedef __n64 poly8x8_t;

/* 23 */
typedef __n64 poly16x4_t;

/* 24 */
typedef __n128 poly16x8_t;

/* 25 */
typedef __n128 poly8x16_t;

/* 26 */
typedef __n64 float32x2_t;

/* 27 */
typedef __n128 float32x4_t;

/* 28 */
typedef __n128 float64x2_t;

/* 29 */
typedef __n128 poly128_t;

/* 30 */
struct __va_list_tag
{
  void *__stack;
  void *__gr_top;
  void *__vr_top;
  int __gr_offs;
  int __vr_offs;
};

/* 31 */
typedef __va_list_tag gcc_va_list[1];

/* 32 */
typedef union $955F1759725876F7F898C71A8A4DCDA3 pthread_mutex_t;

/* 36 */
struct __pthread_internal_list
{
  struct __pthread_internal_list *__prev;
  struct __pthread_internal_list *__next;
};

/* 35 */
typedef struct __pthread_internal_list __pthread_list_t;

/* 34 */
struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  unsigned int __nusers;
  int __kind;
  int __spins;
  __pthread_list_t __list;
};

/* 33 */
union $955F1759725876F7F898C71A8A4DCDA3
{
  struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s __data;
  char __size[40];
  __int64 __align;
};

/* 37 */
typedef union $1C4035FDEAFFF0FCE26E66A96F6BBEB4 pthread_cond_t;

/* 39 */
struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E
{
  int __lock;
  unsigned int __futex;
  unsigned __int64 __total_seq;
  unsigned __int64 __wakeup_seq;
  unsigned __int64 __woken_seq;
  void *__mutex;
  unsigned int __nwaiters;
  unsigned int __broadcast_seq;
};

/* 38 */
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4
{
  struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E __data;
  char __size[48];
  __int64 __align;
};

